### ISSUE TITLE
Request - Address validation API call

### ISSUE THREAD

**Issue by Dayjo** [OpenSRS/osrs-toolkit-php#12]
Hello!

We're currently trying to create a better UX for our users when purchasing domains, one of the issues is the necessity for us to have a manual process for registering / refunding users when they enter incorrect address information and then try and register a domain.

As there doesn't seem to be a way to verify the address details BEFORE the registration request, this causes issues as we have taken the user's money, but don't know until after that their address was invalid, this means we have to manually refund them, or ask them for valid address details and manually register the domain. 

It'd be great if there was a command to 'check' a call. With Nominet's EPP there's the "check" command which allows you to request "I would like to register this domain, with these details, will this work?", and if it fails, you can show the appropriate errors to the user for them to fix before they continue to purchase and actually register the domain.

Regards,

Joel

**Comment by colincode** [comment]
I believe you should be able to accomplish what you are looking for by using the "save" option to the handle attribute in your register call.

Save puts your registration into a pending queue, and runs the validation on the request, without actually doing the register.  (at least it did when I treid it)

You can then make a follow up call to process_pending, passing along the id returned in the "save" response.  This will do the final registration step for you.

Hope this helps.

**Comment by Dayjo** [comment]
Interesting idea @colincode. I may propose a similar solution. I guess the trick would be to ensure they get 'removed' or 'cancelled' if the user doesn't complete the purchase. At the moment we do have some manual processes involving creating domains like that so we'd have to take them into account.

Thanks for the suggestion!
