### ISSUE TITLE
E.T.A. for Composer Support

### ISSUE THREAD

**Issue by bonnerl** [OpenSRS/osrs-toolkit-php#13]
I'm doing some initial research in preparation for using the OpenSRS API and I'm wondering when you will finish adding support for Composer? I see that you've started adding Composer support on the [develop branch](OpenSRS/osrs-toolkit-php/tree/develop). Do you have an E.T.A. for either beta or production support?

**Comment by colincode** [comment]
No official timeline as of yet for a release with composer support.  Feel free to try it out from the develop branch in the meantime.
