### ISSUE TITLE
problems with composer (structure?)

### ISSUE THREAD

**Issue by kg00** [OpenSRS/osrs-toolkit-php#21]
New to composer but since I want to replace the standard API we use today for opensrs, I had to start using it ...
Installed composer with no problems
Created a folder called projects and executed:
`composer require opensrs/osrs-toolkit-php in that folder`
The structure created was a bit confusing (sorry, but I don't know how to indent in this editor) :
projects
_ vendor
_ _ autoload.php
_ _ composer
_ _ _ autoload files
_ _ opensrs
_ _ _ osrs_toolkit_php
_ _ _ _ composer.json
_ _ _ _ demo
_ _ _ _ _ dirs and files
_ _ _ _ opensrs
_ _ _ _ _ dirs and files

Is this really correct?

Added the openSRS_config.php with correct settings.

Tested to go to http://mydomain.tld/projects/vendor/opensrs/osrs-toolkit-php/demo/
OK

Clicking on Lookup domain and it shows the page
http://mydomain.tld/projects/vendor/opensrs/osrs-toolkit-php/demo/testcase/test-lookupDomain.php?format=json
OK

Entering a domain and clicking on the Check button:
Not OK. error_log in demo/testcase/ shows that it cant find the autoloader:

`require(/home/mydomain/public_html/projects/vendor/opensrs/osrs-toolkit-php/opensrs/../vendor/autoload.php): failed to open stream: No such file or directory in /home/mydomain/public_html/projects/vendor/opensrs/osrs-toolkit-php/opensrs/openSRS_loader.php on line 3`

To be sure it was not a problem on the Linux server, I set up a windows version as well, but got the same errors

Please advise

//kg00

**Comment by kg00** [comment]
Update:
Tried the code you have in the readme file for using the toolkit [https://github.com/OpenSRS/osrs-toolkit-php#using-the-toolkit](url) but got the following error:
`PHP Fatal error:  Class 'Request' not found in /home/mydomain/public_html/opensrstest_12.php on line 6`

Did a print_r( spl_autoload_functions() ) and it shows /home/mydomain/public_html/projects/vendor/opensrs/osrs-toolkit-php/opensrs:

Array
(
    [0] => Array
        (
            [0] => Composer\Autoload\ClassLoader Object
                (
                    [prefixLengthsPsr4:Composer\Autoload\ClassLoader:private] => Array
                        (
                            [o] => Array
                                (
                                    [opensrs\] => 8
                                )
                        )
                    [prefixDirsPsr4:Composer\Autoload\ClassLoader:private] => Array
                        (
                            [opensrs\] => Array
                                (
                                    [0] => /home/mydomain/public_html/projects/vendor/opensrs/osrs-toolkit-php/opensrs
                                )
                        )
                    [fallbackDirsPsr4:Composer\Autoload\ClassLoader:private] => Array
                        (
                        )
                    [prefixesPsr0:Composer\Autoload\ClassLoader:private] => Array
                        (
                        )
                    [fallbackDirsPsr0:Composer\Autoload\ClassLoader:private] => Array
                        (
                        )
                    [useIncludePath:Composer\Autoload\ClassLoader:private] => 
                    [classMap:Composer\Autoload\ClassLoader:private] => Array
                        (
                        )
                    [classMapAuthoritative:Composer\Autoload\ClassLoader:private] => 
                )
            [1] => loadClass
        )
)

**Comment by kg00** [comment]
Changed openSRS_loader.php from:
`require dirname(__FILE__).'/../vendor/autoload.php';`
 to:
`require dirname(__FILE__).'/../../../../vendor/autoload.php';`
and now it seems to work.

(same issue in all demo-files having the require for autoload)

Did I something wrong when installing the toolkit that put the autoload.php in the wrong place?

**Comment by davey-g** [comment]
Totally agree with the structure, its complete pants!

Just downloaded everything via composer, and the paths are all over the place. Nothing works.
You sort one file out, only to find another is wrong.

Even tried moving the demo folder down a few levels, but this made things worse, as it was referencing something else deeper down the path.

**Comment by colincode** [comment]
We never imagined the demo to be run from a composer install.  The demo folder is primarily intended as developer tool, to test checked out code.

With added test coverage, I'm going to re-asses if the demo even make sense to be included in this repo at all.  At the very least I'll try and make this more clear in the documentation.  Sorry for any confusion.

**Comment by swiftinternetdesign** [comment]
Could you then provide a working demo, so we can try to understand how it all should work please.

**Comment by colincode** [comment]
Yes, I do see value in it.  The demo samples helped me when I started looking at this code.  I'll see what I can do to make running the demo samples more clear.

In the meantime...

If you have question about getting the library itself to do something specific for you, feel free to ask. I can maybe provide a snippet, or some guidance that may be quicker than you toiling around with the demo code.

**Comment by swiftinternetdesign** [comment]
Yes a snippet would be great, thanks
We are looking to register domains via EPP as we currently do with Nominet. However as mentioned in my previous comment - the EPP script we have for Nominet is just a single php class - so trying to understand this is very daunting for me.

**Comment by Dayjo** [comment]
@swiftinternetdesign  The way I've done this in the past is with the following structure;

## Domain class
This is overarching class which handles simple commands and chooses which 'registrar' class to use. For instance;

```php
public static function register( $domain, $period = 2 ) {
   // Depending on the TLD, run the Nominet::register function or OpenSRS::register function
}
```

## Registar interface
This would be an interface used by all registrar classes and contains a list of standardised functions i.e. `register( $domain, $period )`.

This helps with standardising responses, errors (which can/has been a nightmare)

## Nominet class
This is a custom class based on the Registrar interface which calls the official Nominet EPP class (which was horrible the last time I used it) 

## OpenSRS class
This is a custom class based on the Registrar interface which calls the official OpenSRS SDK functions needed as per the Nominet one.

-----

Then your EPP class and the OpenSRS toolkit are just standalone dependencies.

**Comment by colincode** [comment]
`
<?php

// require composer autloader
require_once './vendor/autoload.php';

// require your config file
require_once './openSRS_config.php';

// import OpenSRS Requests
use opensrs\Request;

// Use the same contact data
$contact = array(
    'first_name' => 'John',
    'last_name' => 'Smith',
    'org_name' => 'Tucows',
    'address1' => '96 Mowat Avenue',
    'address2' => '',
    'address3' => '',
    'city' => 'Toronto',
    'state' => 'ON',
    'country' => 'CA',
    'postal_code' => 'M6K 3M1',
    'phone' => '+1.4165350123',
    'email' => 'phptoolkit@tucows.com',
    'lang_pref' => 'EN'
);

// build request data (shown with array, but you can use json as well)
$data = array(
    'func' => 'provswregister',
    'attributes' => array(
        'domain' => 'phptest'.time().'.com',
        'contact_set' => array(
            'owner' => $contact,
            'admin' => $contact,
            'billing' => $contact,
            'tech' => $contact
        ),
        'custom_nameservers' => '0',
        'custom_tech_contact' => '0',
        'handle' => 'save',
        'period' => '1',
        'reg_username' => 'jsmith',
        'reg_password' => 'password1234!',
        'reg_type' => 'new',
    ),
);

try {
    // submit request
    $request = new Request();
    $osrsHandler = $request->process('array', $data);

    // do something with response
    var_dump($osrsHandler->resultRaw);

} catch(Exception $e) {
    // handle error
    var_dump($e->getMessage());
}
`

**Comment by colincode** [comment]
I've updated the docs in the wiki to better explain how to get the demo up and running with Vagrant.
