### ISSUE TITLE
Error - lookupGetDomainsByExpiry

### ISSUE THREAD

**Issue by TomMalbran** [OpenSRS/osrs-toolkit-php#23]
I was getting an error when trying to access the "lookupGetDomainsByExpiry" route and I found that the issue is that there is a missing "i" on both the route and the class name on RequestFactory.

Here is that line:
https://github.com/OpenSRS/osrs-toolkit-php/blob/master/opensrs/RequestFactory.php#L13

**Comment by colincode** [comment]
Good catch!  Updated in master.
