### ISSUE TITLE
Provide specific contact details using provSWregister function

### ISSUE THREAD

**Issue by rkingy** [OpenSRS/osrs-toolkit-php#28]
Hi,

We are needing to provide specific contact information for Owner, Admin, Billing and Tech.
I noticed an example with a personal array of information, but we'd prefer to use the contact_set as specified in the documentation.

My solution was to edit the /opensrs/backwardcompatibility/dataconversion/domains/provisioning/SWRegister.php newStructure array to include this.

`'contact_set' => array(
                'owner' => 'data->contact_set->owner',
                'admin' => 'data->contact_set->admin',
                'billing' => 'data->contact_set->billing',
                'tech' => 'data->contact_set->tech',
                ),`

Instead of 

`'contact_set' => array(
                'owner' => 'data->personal',
                'admin' => 'data->personal',
                'billing' => 'data->personal',
                'tech' => 'data->personal',
                ),`

Is that the best way to do this? I'm sure others will be wanting this functionality. I recommend using the contact_set options if personal isn't set.

**Comment by rkingy** [comment]
Ok bit of an update here.. I discovered through trial and error (This needs to be clearer in the documentation) that the way I was making my requests was using the backwards compatible mode. Where as the newer functions support the contact set correctly.

**Comment by vladimirbasic** [comment]
@rkingy I have the same issue here. I want to be able to define all four contacts independently. Can you give me an example of what the payload should look like when you are sending it to the **process** method of **opensrs\Request** object?

Thanks a lot.

**Comment by vladimirbasic** [comment]
@rkingy I forgot to mention that I am using **provSWregister** function for registering a new domain.
