### ISSUE TITLE
Error with provModify validation

### ISSUE THREAD

**Issue by pb30** [OpenSRS/osrs-toolkit-php#32]
Trying to modify a domain to change autorenew settings but can't seem to find the right syntax.

```
$callArray = array(
        'func' => 'provModify',
        'data' => [
                'domain'         => $_GET['domain'],
                'affect_domains' => 0,
                'data' => [
                        'auto_renew'     => 0,
                        'let_expire'     => 1,
                ]
        ],
);

try {
    $request = new Request();
    /** @var \opensrs\Base $osrsHandler */
    $osrsHandler = $request->process('array', $callArray);
    var_dump($osrsHandler->resultRaw);
} catch (\opensrs\Exception $e) {
    var_dump($e->getMessage());
}
```

Produces PHP Warning:

> Warning: strlen() expects parameter 1 to be string, object given in /vweb/www.afsb.net/vendor/opensrs/osrs-toolkit-php/opensrs/Base.php on line 489

And API error:
> oSRS Error - data is not defined.

**Comment by Dayjo** [comment]
Can you verify the contents of $_GET['domain'] ?

**Comment by pb30** [comment]
Same results:

```
$callArray = array(
        'func' => 'provModify',
        'data' => [
                'domain'         => 'pbtestdomain.com',
                'affect_domains' => 0,
                'data' => [
                        'auto_renew'     => 0,
                        'let_expire'     => 1,
                ]
        ],
);
```

**Comment by pb30** [comment]
Getting same error when updating to use dev-master (2ea736f)

**Comment by detain** [comment]
it needs to be
$callArray = array(
        'func' => 'provModify',
        'attributes' => [
                'domain'         => 'pbtestdomain.com',
                'data' => 'expire_action',
                'affect_domains' => 0,
                'auto_renew'     => 0,
                'let_expire'     => 1,
        ]
);
i believe

**Comment by pb30** [comment]
Looks like that works, thanks!
