### ISSUE TITLE
PHP 7/7.1 Issues with String and Integer concat

### ISSUE THREAD

**Issue by Sladewill** [OpenSRS/osrs-toolkit-php#36]
https://github.com/OpenSRS/osrs-toolkit-php/blob/15d2d8c2fbd8edb54d919deba1661cca2a1a4134/opensrs/Ops.php#L196

With this line of code php throws an error, surely this should use the . to combine the variables together.

**Comment by developernaren** [comment]
@Sladewill this is giving me issues while upgrading php version. How did you get rid of the issue?

**Comment by Sladewill** [comment]
I believe we forked it and used our own private repo.

**Comment by developernaren** [comment]
I did same for the moment. But this is really weird. There is even a PR with a change to fix this, but it is not merged. The issue is more than a year old.

**Comment by Sladewill** [comment]
I believe the project has been abandoned considering the last activity was April 2017.

**Comment by tracer99** [comment]
Tracked in #38
