### ISSUE TITLE
Lookup Domain Validation Bug

### ISSUE THREAD

**Issue by Brookesa05** [OpenSRS/osrs-toolkit-php#41]
The docs say that the lookup domain function should be passed "domain" => example.com but this always returns the error "oSRS Error - domain is not defined". Looked into the validation and searchString is expected instead. The comment above the $newStructure array suggests that domain is correct and not searchString backed up by the api docs.

Issue is in vendor\opensrs\osrs-toolkit-php\opensrs\backwardcompatibility\dataconversion\domains\lookup\LookupDomain.php on line 28

change from 'domain' => 'data->searchString', to 'domain' => 'data'->domain

**Comment by arekpietrzyk** [comment]
[API Quick Start Guide](https://domains.opensrs.guide/docs/lookup-domain) tells us that **domain** parameter should be one of the **attributes** array elements.

Example code should look like:
```
$response = $request->process('array', [
	'func' => 'lookupdomain',
	'attributes' => [
		'domain' => 'example.com',
	],
]);
```
