### ISSUE TITLE
oSRS Error - UNEXPECTED READ: Unable to parse HTTP response code. Please make sure IP is whitelisted in RWI.

### ISSUE THREAD

**Issue by TarnjeetIron** [OpenSRS/osrs-toolkit-php#43]
I have successfully implement this toolkit on my local with php 5.6 version. Its works fine. But when I move it to server where php 7 is installed then it gives me this error. Have any idea about that?

**Comment by arekpietrzyk** [comment]
You need to whitelist IP addresses from where your requests are sent.

According to API Quick Start Guide:

"On the Account Settings page, scroll down to IP Access Rules and select the edit button. Here, you can add the IP address from which you will send API calls."
