### ISSUE TITLE
echo $callCheck . "<br/>";

### ISSUE THREAD

**Issue by jpswade** [OpenSRS/osrs-toolkit-php#9]
Hi there,

On line 67 of opensrs/openSRS_fastlookup.php you will find the following:

```echo $callCheck . "<br/>";```

https://github.com/OpenSRS/osrs-toolkit-php/blob/master/opensrs/openSRS_fastlookup.php#L67

This appears to be debug code that has accidentally been left in for production.

This line should be removed.

**Comment by colincode** [comment]
Fixed by Nikul with 6d903c93bf3f5f309dc5e566bee406a5882aaba2
